config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:new, :create]

  root to: 'visitors#index'

  devise_scope :user do
    # get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    delete "/logout" => "devise/sessions#destroy"
    # get "/signup" => "devise/registrations#new"
    # get "/settings" => "devise/registrations#edit"
  end

  devise_for :users
  resources :users

  # get 'about' => 'pages#about'
  # get 'blog' => 'pages#blog'
  # get 'contact' => 'pages#contact'

  Rails.application.routes.draw do
  get 'messages/new'

    # get "/:page" => "pages#show"
  end

end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :subject, :content
  validates :name, :email, :subject, :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.message_me(@message).deliver_now
      flash[:success] = 'Your message was sent successfully!'
      redirect_to new_message_path
      # redirect_to new_message_path, flash[:notice] = "Thank you for your message."
    else
      render :new
    end
  end



  private

  def message_params
    params.require(:message).permit(:name, :email, :subject, :content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    render template: "pages/#{params[:page]}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<!--&lt;!&ndash; Footer &ndash;&gt;-->
<!--<footer>-->
    <!--<div class="container">-->
        <!--<div class="row">-->
            <!--<div class="col-lg-12 text-center">-->
                <!--<p>Copyright &copy; Your Website 2014</p>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
<!--</footer>-->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<%# flash.each do |name, msg| %>
  <%# if msg.is_a?(String) %>
    <!--<div class="alert alert-<%#= name.to_s == 'notice' ? 'success' : 'danger' %>">-->
      <!--<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>-->
      <%#= content_tag :div, msg, :id => "flash_#{name}" %>
    <!--</div>-->
  <%# end %>
<%# end %>

app/views/layouts/_nav_links_for_auth.html.erb
<%# if user_signed_in? %>
  <!--<li><%#= link_to 'Edit account', edit_user_registration_path %></li>-->
  <!--<li><%#= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>-->
<%# else %>
  <!--<li><%#= link_to 'Sign in', new_user_session_path %></li>-->
  <!--<li><%#= link_to 'Sign up', new_user_registration_path %></li>-->
<%# end %>

app/views/layouts/_navbar.html.erb
<!--Navbar-->
<nav class="navbar navbar-dark navbar-fixed-top scrolling-navbar">

  <!-- Collapse button-->
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#collapseEx">
    <i class="fa fa-bars"></i>
  </button>

  <div class="container">

    <!--Collapse content-->
    <div class="collapse navbar-toggleable-xs" id="collapseEx">
      <!--Navbar Brand-->
      <a class="navbar-brand" href="/">Home</a>
      <!--Links-->
      <!--<ul class="nav navbar-nav smooth-scroll"> TODO: USE SMOOTH-SCROLL TO SCROLL ON PAGE-->
      <ul class="nav navbar-nav">
        <!--<li class="nav-item active">-->
        <!--<a class="nav-link" href="#home">Home <span class="sr-only">(current)</span></a>-->
        <!--</li>-->
        <li class="nav-item">
          <a class="nav-link" href="../pages/service_menu.html.erb">Service Menu</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="../messages/new">Contact</a>
        </li>
        <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#testimonials">Photoshoot Glam</a>-->
        <!--</li>-->
        <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#pricing">Pricing</a>-->
        <!--</li>-->
        <!--<li class="nav-item">-->
        <!--<a class="nav-link" href="#contact">Contact</a>-->
        <!--</li>-->
      </ul>
    </div>
    <!--/.Collapse content-->

  </div>

</nav>
<!--/.Navbar-->

app/views/layouts/_navigation.html.erb
 <!--Navigation-->
<!--<nav class="navbar navbar-default" role="navigation">-->
    <!--<div class="container">-->
        <!--&lt;!&ndash; Brand and toggle get grouped for better mobile display &ndash;&gt;-->
        <!--<div class="navbar-header">-->
            <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">-->
                <!--<span class="sr-only">Toggle navigation</span>-->
                <!--<span class="icon-bar"></span>-->
                <!--<span class="icon-bar"></span>-->
                <!--<span class="icon-bar"></span>-->
            <!--</button>-->
            <!--&lt;!&ndash; navbar-brand is hidden on larger screens, but visible when the menu is collapsed &ndash;&gt;-->
            <!--<%#= link_to 'Business Casual', root_path, class: 'navbar-brand' %>-->
        <!--</div>-->
        <!--&lt;!&ndash; Collect the nav links, forms, and other content for toggling &ndash;&gt;-->
        <!--<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->
            <!--<ul class="nav navbar-nav">-->
                <!--<%#= render 'layouts/navigation_links' %>-->
        <!--<%#= render 'layouts/nav_links_for_auth' %>-->
            <!--</ul>-->
        <!--</div>-->
        <!--&lt;!&ndash; /.navbar-collapse &ndash;&gt;-->
    <!--</div>-->
    <!--&lt;!&ndash; /.container &ndash;&gt;-->
<!--</nav>-->

app/views/layouts/_navigation_links.html.erb
<%## add navigation links to this file %>
<!--<li>-->
    <!--<%#= link_to 'Home', root_path %>-->
<!--</li>-->
<!--<li>-->
    <!--<%#= link_to 'About', page_path('about') %>-->
<!--</li>-->
<!--<li>-->
    <!--<%#= link_to 'Blog', page_path('blog') %>-->
<!--</li>-->
<!--<li>-->
    <!--<%#= link_to 'Contact', page_path('contact') %>-->
<!--</li>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield(:heading) %>
    <!-- Custom Fonts -->
    <!--<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">-->
    <!--<link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">-->
    <link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
  </head>
  <body>
      <%= render 'layouts/messages' %>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

      <%= yield(:main) %>
      <%= render 'layouts/footer' %>
      <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= yield(:javascript) %>
  </body>
</html>

app/views/messages/new.html.erb
<% content_for :main do %>

  <%= stylesheet_link_tag 'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'mdb.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'style_landing', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'demo', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">

  <%= render 'layouts/navbar' %>

  <!--Naked Form-->
  <div class="card-block">

    <!--Header-->
    <div class="text-xs-center">
      <br /><br /><br /><br /><h3>Create message:</h3>
      <hr class="m-t-2 m-b-2">
    </div>

    <!--Body-->
    <!--<p>We'll write rarely, but only the best content.</p>-->
    <br>

    <!--Body-->

    <%= form_for @message do |f| %>
    <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
      </h2>

      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <!--<form action="/messages" method="post">-->
    <div class="md-form">
      <i class="fa fa-user prefix"></i>
      <%= f.text_field :name, id: "form3", class:"form-control"%>
      <%= f.label :name, type: "text", for:"form3" %>
      <!--<input type="text" id="form3" class="form-control">-->
      <!--<label for="form3">Your name</label>-->
    </div>

    <div class="md-form">
      <i class="fa fa-envelope prefix"></i>
      <%= f.text_field :email, id: "form2", class:"form-control"%>
      <%= f.label :email, type: "text", for:"form2" %>
      <!--<input type="text" id="form2" class="form-control">-->
      <!--<label for="form2">Your email</label>-->
    </div>

    <div class="md-form">
      <i class="fa fa-tag prefix"></i>
      <%= f.text_field :subject, id: "form32", class:"form-control"%>
      <%= f.label :subject, type: "text", for:"form34" %>
      <!--<input type="text" id="form32" class="form-control">-->
      <!--<label for="form34">Subject</label>-->
    </div>

    <div class="md-form">
      <i class="fa fa-pencil prefix"></i>
      <%= f.text_field :content, id: "form8", class:"md-textarea text-box-larger"%>
      <%= f.label :content, type: "text", for:"form3" %>
      <!--<textarea type="text" id="form8" class="md-textarea"></textarea>-->
      <!--<label for="form8">Icon Prefix</label>-->
    </div>

    <div class="text-xs-center">
      <%= f.submit 'Submit', class: 'btn btn-default', type: "submit" %>
      <!--<button class="btn btn-default" type="submit" >Submit</button>-->
    <%# end %>

      <div class="call">
        <br>
        <p>Or would you prefer to call?
          <br>
          <span><i class="fa fa-phone"> </i></span>(916)501-1220</p>
      </div>
    </div>
    <!--</form>-->
  <% end %>
  </div>
  <!--Naked Form-->

<%#= form_for @message do |f| %>
  <%# if @message.errors.any? %>
    <!--<div id="error_explanation">-->
      <!--<h2>-->
        <!--<%#= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>-->
      <!--</h2>-->

      <!--<ul>-->
        <!--<%# @message.errors.full_messages.each do |msg| %>-->
          <!--<li><%#= msg %></li>-->
        <!--<%# end %>-->
      <!--</ul>-->
    <!--</div>-->
  <!--<%# end %>-->

  <!--<div class="field">-->
    <!--<%#= f.label :name %>-->
    <!--<%#= f.text_field :name %>-->
  <!--</div>-->

  <!--<div class="field">-->
    <!--<%#= f.label :email %>-->
    <!--<%#= f.email_field :email %>-->
  <!--</div>-->

  <!--<div class="field">-->
    <!--<%#= f.label :subject %>-->
    <!--<%#= f.text_field :subject %>-->
  <!--</div>-->

  <!--<div class="field">-->
    <!--<%#= f.label :content %>-->
    <!--<%#= f.text_area :content %>-->
  <!--</div>-->

  <!--<div class="actions">-->
    <!--<%#= f.submit 'Send', class: 'button' %>-->
  <!--</div>-->
<%# end %>

<% end %>

<% content_for :javascript do %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'google_analytics', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'mdb.min', 'data-turbolinks-track' => true %>

<% end %>

app/views/pages/extension_color_gallery.html.erb
<% content_for :title do %>
  "Casey Carr - Color Image Gallery"
<% end %>
<% content_for :heading do %>
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <!--<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">-->
      <!--<meta name="description" content="Responsive Image Gallery with jQuery" />-->
      <!--<meta name="keywords" content="jquery, carousel, image gallery, slider, responsive, flexible, fluid, resize, css3" />-->
      <!--<meta name="author" content="Codrops" />-->
      <!--<link rel="shortcut icon" href="../favicon.ico">-->
  <%= stylesheet_link_tag 'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'mdb.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'style_landing', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag 'demo', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'elastislide', media: 'all', 'data-turbolinks-track' => true %>
      <!--<link rel="stylesheet" type="text/css" href="../../../app/assets/stylesheets/demo.css" />-->
      <!--<link rel="stylesheet" type="text/css" href="../../../app/assets/stylesheets/style.css" />-->
      <!--<link rel="stylesheet" type="text/css" href="../../../app/assets/stylesheets/elastislide.css" />-->
      <link href='https://fonts.googleapis.com/css?family=PT+Sans+Narrow&v1' rel='stylesheet' type='text/css' />
      <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css' />
      <noscript>
        <style>
          .es-carousel ul{
            display:block;
          }
        </style>
      </noscript>
      <script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">
      <div><a class="btn btn-primary center-image" href="https://www.instagram.com/caseycarr/">See more on Instagram!</a></div>
			<div class="rg-image-wrapper">
				{{if itemsCount > 1}}
					<div class="rg-image-nav">
						<a href="#" class="rg-image-nav-prev">Previous Image</a>
						<a href="#" class="rg-image-nav-next">Next Image</a>
					</div>
				{{/if}}
				<div class="rg-image"></div>
				<div class="rg-loading"></div>
				<div class="rg-caption-wrapper">
					<div class="rg-caption" style="display:none;">
						<p></p>
					</div>
				</div>
			</div>
		</script>
<% end %>
<% content_for :main do %>

<%= render 'layouts/navbar' %>

    <div class="container">

      <div class="content">
        <h1> <span id="bring-front">Extension & Color Gallery</span></h1>
        <div id="rg-gallery" class="rg-gallery">
          <div class="rg-thumbs">
            <!-- Elastislide Carousel Thumbnail Viewer -->
            <div class="es-carousel-wrapper">
              <div class="es-nav">
                <span class="es-nav-prev">Previous</span>
                <span class="es-nav-next">Next</span>
              </div>
              <div class="es-carousel">
                <ul>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/1.jpg", alt: "image01", data: { large: asset_path('color_gallery/1.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/2.jpg", alt: "image02", data: { large: asset_path('color_gallery/2.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/3.jpg", alt: "image03", data: { large: asset_path('color_gallery/3.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/4.jpg", alt: "image04", data: { large: asset_path('color_gallery/4.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/5.jpg", alt: "image05", data: { large: asset_path('color_gallery/5.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/6.jpg", alt: "image06", data: { large: asset_path('color_gallery/6.jpg'), description: ""}) %></a></li>
                  <!--<li><a href="#"><%#= image_tag("color_gallery/thumbs/7.JPG", alt: "image07", data: { large: asset_path('color_gallery/7.JPG'), description: ""}) %></a></li>-->
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/8.jpg", alt: "image08", data: { large: asset_path('color_gallery/8.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/9.jpg", alt: "image09", data: { large: asset_path('color_gallery/9.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/10.jpg", alt: "image10", data: { large: asset_path('color_gallery/10.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/11.JPG", alt: "image11", data: { large: asset_path('color_gallery/11.JPG'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/12.jpg", alt: "image12", data: { large: asset_path('color_gallery/12.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/13.jpg", alt: "image13", data: { large: asset_path('color_gallery/13.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/14.jpg", alt: "image14", data: { large: asset_path('color_gallery/14.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/15.jpg", alt: "image15", data: { large: asset_path('color_gallery/15.jpg'), description: ""}) %></a></li>
                  <li><a href="#"><%= image_tag("color_gallery/thumbs/16.jpg", alt: "image16", data: { large: asset_path('color_gallery/16.jpg'), description: ""}) %></a></li>
                </ul>
              </div>
            </div>
            <!-- End Elastislide Carousel Thumbnail Viewer -->
          </div><!-- rg-thumbs -->
        </div><!-- rg-gallery -->
        <a href="javascript:history.back()"><span id="back"><br><<   Back to home</span></a><br><br>
      </div><!-- content -->
    </div><!-- container -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'google_analytics', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'mdb.min', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'jquery.tmpl.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.easing.1.3', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.elastislide', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'gallery', 'data-turbolinks-track' => true %>
    <!--<script type="text/javascript" src="js/jquery.tmpl.min.js"></script>-->
    <!--<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>-->
    <!--<script type="text/javascript" src="js/jquery.elastislide.js"></script>-->
    <!--<script type="text/javascript" src="js/gallery.js"></script>-->
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <p class="logged_in">Logged In As: <%= link_to current_user.email, edit_user_registration_path %> <span style="float:right;"><%= link_to "Sign out", logout_path, :method => :delete %></span></p>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>